### ISSUE TITLE
ConcurrentStrandExecutor - unnecessary breaks and readability

### ISSUE THREAD

**Issue by StefanGsi** [molr/molr#48]
1. While playing around with breakpoints I noticed that the ConcurrentStrandExecutor lifecycle() adds unnecessary sleeps between tasks.

Let's consider a sequential sequence of tasks, A-B-C-D. After executing each task the StrandExecutor sleeps. A-sleep-B-sleep-C-sleep-D. This might not be a relevant issue for our sequencer service, since the default waiting time is only 10ms. But considering sequences with a large number of tasks, those sleeps may add up to an annoying overall waiting time.

2. The fixme comment should be addressed. Moving the ExecutorState based behavior into state-classes could possibly be a way to introduce better readability.

**Comment by andreacalia** [comment]
Dear Stefan,

the `ConcurrentStrandExecutor` should be refactored a bit I agree :slightly_smiling_face: 
Regarding your first point, indeed your right that there is a sleep between every iteration of the lifecycle. This was introduced to liberate some CPU so that a strand in idle/waiting would not eat CPU cycles. The decision of 10ms was completely arbitrary and, as pointed out in the comment of the cycleSleep method, it should be a configurable parameter :smile: (I still think that some sleep or at least a yield should be necessary there)

Your second point is also a good one. The lifecycle is quite long at the moment but I would be careful with refactoring. At the moment is a linear method with clear conditions and naming. Moving to different classes (state-machine like) would be more design pattern compliant but I'm afraid that it will split the logic between different classes and thus will be more difficult to follow (you kind of loose the "overview"). Anyway, I would evaluate that only after careful unit testing, I think it should be quite ok at the moment, but maybe after using it for a while you'll find some behaviour you might want to unit test, so they become more bullet proof during refactoring :slightly_smiling_face:

**Comment by kaifox** [comment]
Concerning the first point:
Is Thread.sleep() really the right thing to do this? Does it really liberate the thread? I thought, one rather would have to use some  wait()- construct

Concerning the refactoring: I tend to agree with Andrea for the moment: keeping the logic in one central place seems to be a good idea for the moment (rather refactor some methods out that the lifecycle method still stays short)... However, improving test converage and the try tome refactoring is still a good idea in the longer term ...

**Comment by StefanGsi** [comment]
Regarding the sleeps: 
I agree that the sleeps are useful while waiting for commands etc., e.g. while the strand is paused. But a sleep seems pointless as long as tasks are scheduled and could be executed immediately.

Refactoring:
OK, thanks for your comments.

**Comment by kaifox** [comment]
Hi Guys, 
for further follow up, I split this issue in 2:
* Sleeps: #49 
* Refactoring: #50 

I will close this one.
